name: Metrics
on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics (left)
        uses: lowlighter/metrics@latest
        if: ${{ success() || failure() }}
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.left.svg
          base: header
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, percentage
          plugin_languages_ignored: dockerfile, makefile, shell
          plugin_languages_skipped: ar-cards, minecraft-among-us, skyblock-confinement
          plugin_languages_limit: 5
          plugin_habits: yes
          config_order: base.header, isocalendar, languages, habits
          config_timezone: Europe/Paris
