name: Metrics
on:
  schedule:
    - cron: "20 4 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        if: ${{ success() || failure() }}
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_ignored: dockerfile, makefile, shell
          plugin_languages_skipped: ar-cards, minecraft-among-us, skyblock-confinement
          plugin_languages_limit: 6
          plugin_habits: yes
          plugin_habits_days: 30
          plugin_habits_charts: yes
          plugin_habits_charts_type: chartist
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: e36ce5b786fd4d0db49234628f54c8d2,${{ secrets.METRICS_SPOTIFY_CLIENT_SECRET }},${{ secrets.METRICS_SPOTIFY_REFRESH_TOKEN }}
          plugin_music_mode: top
          plugin_music_limit: 5
          plugin_activity: yes
          plugin_activity_limit: 10
          plugin_activity_days: 30
          plugin_activity_visibility: public
          config_order: base.header, languages, habits, music, activity
          config_timezone: Europe/Paris
      - name: Metrics (skyline)
        uses: lowlighter/metrics@latest
        if: ${{ success() || failure() }}
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.bottom.svg
          base: ""
          plugin_skyline: yes
          plugin_skyline_frames: 60
          plugin_skyline_quality: 1
          plugin_skyline_compatibility: yes
          config_timezone: Europe/Paris
